### ISSUE TITLE
[Task] Module03 - worflow error in the path to the exec of the unit tests

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Module03#21]
### Title

Path to exec file for tests

### Description

Modify the path to the exec file to run the unit tests.

### Priority

High

### Checklist

- [ ] Change path to exec file

### Epic Reference

SEAME-pt/Team02-WarmUp#18

**Comment by luis-ffe** [comment]
I will now work on this.

**Comment by luis-ffe** [comment]
# Closed
